#!/usr/bin/env python3
# Generated by Antigravity CLI 1.1.25 (Gemini 3.8 Flash (High))
"""
Unit and integration tests for git-prompt-log.
"""

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

import importlib.machinery
from pathlib import Path
bin_path = Path(__file__).resolve().parent.parent / "bin" / "git-prompt-log"
gpn = importlib.machinery.SourceFileLoader("git_prompt_log", str(bin_path)).load_module()
gpl = gpn


class TestNoteParsingAndFormatting(unittest.TestCase):
    def test_single_session_parse_and_format(self):
        raw = """Assistant-Session: 9674eda6-390f-4b1d-9910-72bec1843401
Assistant-Harness: Antigravity CLI 1.1.25
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-04 01:03:57 UTC

Assistant-Prompts:
  [2026-09-04 01:03:57] Make the camera pivot around the ball origin
  [2026-09-04 01:09:25]
    Let's implement this.
    Second line of prompt.
"""
        notes = gpn.parse_notes(raw)
        self.assertEqual(len(notes), 1)
        n = notes[0]
        self.assertEqual(n.session_id, "9674eda6-390f-4b1d-9910-72bec1843401")
        self.assertEqual(n.harness, "Antigravity CLI 1.1.25")
        self.assertEqual(n.model, "Gemini 3.8 Flash (High)")
        self.assertEqual(n.recorded_at, "2026-09-04 01:03:57 UTC")
        self.assertEqual(len(n.prompts), 2)
        self.assertEqual(n.prompts[0].timestamp, "2026-09-04 01:03:57")
        self.assertEqual(n.prompts[0].text, "Make the camera pivot around the ball origin")
        self.assertEqual(n.prompts[1].timestamp, "2026-09-04 01:09:25")
        self.assertIn("Second line of prompt.", n.prompts[1].text)

        # Roundtrip formatting
        formatted = gpn.serialize_notes(notes)
        self.assertIn("Assistant-Session:", formatted)
        roundtrip_notes = gpn.parse_notes(formatted)
        self.assertEqual(len(roundtrip_notes), 1)
        self.assertEqual(roundtrip_notes[0].session_id, n.session_id)
        self.assertEqual(len(roundtrip_notes[0].prompts), 2)

    def test_multi_session_parse(self):
        raw = """Assistant-Session: session-aaa
Assistant-Harness: Antigravity CLI 1.1.24
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-01 10:00:00 UTC

Assistant-Prompts:
  [2026-09-01 10:00:00] Initial prompt

---

Assistant-Session: session-bbb
Assistant-Harness: Antigravity CLI 1.1.25
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-04 01:00:00 UTC

Assistant-Prompts:
  [2026-09-04 01:00:00] Followup prompt
"""
        notes = gpn.parse_notes(raw)
        self.assertEqual(len(notes), 2)
        self.assertEqual(notes[0].session_id, "session-aaa")
        self.assertEqual(notes[1].session_id, "session-bbb")

    def test_surrounding_non_prompt_notes_preserved(self):
        raw = """Reviewed and approved by QA team.

Assistant-Session: session-xyz
Assistant-Harness: Antigravity CLI 1.1.25
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-04 01:00:00 UTC

Assistant-Prompts:
  [2026-09-04 01:00:00] Add camera zoom feature

Deploy-ID: 98124
"""
        prefix, block, suffix = gpn.extract_prompt_block(raw)
        self.assertEqual(prefix, "Reviewed and approved by QA team.")
        self.assertEqual(suffix, "Deploy-ID: 98124")
        self.assertIn("Assistant-Session: session-xyz", block)
        self.assertIn("Add camera zoom feature", block)

        parsed = gpn.parse_notes(raw)
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0].session_id, "session-xyz")

        # Rewrapping preserves prefix and suffix
        reconstructed = gpn.wrap_prompt_block(block, prefix=prefix, suffix=suffix)
        self.assertIn("Reviewed and approved by QA team.", reconstructed)
        self.assertIn("Deploy-ID: 98124", reconstructed)


class TestNoteMerging(unittest.TestCase):
    def test_same_session_squash_merge(self):
        note1 = gpn.SessionNote(
            session_id="session-1",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:05:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-04 01:03:57", "First prompt"),
            ],
        )
        note2 = gpn.SessionNote(
            session_id="session-1",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:10:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-04 01:03:57", "First prompt"),  # Duplicate
                gpn.PromptEntry("2026-09-04 01:09:25", "Second prompt"),
            ],
        )

        merged = gpn.merge_session_notes([note1, note2])
        self.assertEqual(len(merged), 1)
        m = merged[0]
        self.assertEqual(m.session_id, "session-1")
        self.assertEqual(m.recorded_at, "2026-09-04 01:10:00 UTC")  # Latest timestamp
        self.assertEqual(len(m.prompts), 2)
        self.assertEqual(m.prompts[0].text, "Second prompt")
        self.assertEqual(m.prompts[1].text, "First prompt")

    def test_cross_session_squash_merge(self):
        note1 = gpn.SessionNote(
            session_id="session-day-1",
            harness="Antigravity CLI 1.1.24",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-01 10:00:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-01 09:50:00", "Prompt from day 1"),
            ],
        )
        note2 = gpn.SessionNote(
            session_id="session-day-2",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:10:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-04 01:09:25", "Prompt from day 2"),
            ],
        )

        merged = gpn.merge_session_notes([note1, note2])
        self.assertEqual(len(merged), 2)
        self.assertEqual(merged[0].session_id, "session-day-1")
        self.assertEqual(merged[1].session_id, "session-day-2")

        serialized = gpn.serialize_notes(merged)
        self.assertIn("Assistant-Session: session-day-1", serialized)
        self.assertIn("Assistant-Session: session-day-2", serialized)
        self.assertIn("\n\n---\n\n", serialized)


class TestGitPostRewriteIntegration(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.mkdtemp()
        self.repo_dir = Path(self.tmp_dir)

        # Initialize git repo
        subprocess.run(["git", "init"], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=self.repo_dir, check=True)

    def tearDown(self):
        shutil.rmtree(self.tmp_dir)

    def _commit(self, filename: str, content: str, msg: str) -> str:
        fpath = self.repo_dir / filename
        fpath.write_text(content)
        subprocess.run(["git", "add", filename], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "commit", "-m", msg], cwd=self.repo_dir, check=True, capture_output=True)
        out = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        return out

    def test_post_rewrite_squash(self):
        sha1 = self._commit("file1.txt", "hello", "Commit 1")
        sha2 = self._commit("file2.txt", "world", "Commit 2")

        # Attach prompt notes to sha1 and sha2
        note1 = gpn.SessionNote(
            session_id="session-test",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:05:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 01:03:00", "Create file 1")],
        )
        note2 = gpn.SessionNote(
            session_id="session-test",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:10:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 01:08:00", "Create file 2")],
        )
        gpn.write_note_content(sha1, note1.format(), repo_root=self.repo_dir)
        gpn.write_note_content(sha2, note2.format(), repo_root=self.repo_dir)

        # Simulate a squash into sha3
        sha3 = self._commit("file3.txt", "squashed", "Squashed Commit")

        # Simulate git post-rewrite stdin:
        # <sha1> <sha3>
        # <sha2> <sha3>
        stdin_data = f"{sha1} {sha3}\n{sha2} {sha3}\n"

        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "post-rewrite"],
            cwd=self.repo_dir,
            input=stdin_data,
            text=True,
            capture_output=True,
        )
        self.assertEqual(res.returncode, 0)

        # Verify sha3 has the merged note
        note_sha3_raw = gpn.get_note_content(sha3, repo_root=self.repo_dir)
        self.assertIsNotNone(note_sha3_raw)
        parsed = gpn.parse_notes(note_sha3_raw)
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0].session_id, "session-test")
        self.assertEqual(len(parsed[0].prompts), 2)
        self.assertEqual(parsed[0].prompts[0].text, "Create file 2")
        self.assertEqual(parsed[0].prompts[1].text, "Create file 1")

    def test_init_installs_hooks_by_default(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertTrue(os.access(hooks_dir / "post-rewrite", os.X_OK))
        # post-commit is installed by default
        self.assertTrue((hooks_dir / "post-commit").exists())
        self.assertTrue(os.access(hooks_dir / "post-commit", os.X_OK))

        # Skill is not installed by default
        skill_file = self.repo_dir / ".agents" / "skills" / "git-prompt-log" / "SKILL.md"
        self.assertFalse(skill_file.exists())

    def test_init_no_post_commit(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init", "--no-post-commit"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertFalse((hooks_dir / "post-commit").exists())

    def test_init_subcommand_defaults_to_no_skill(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertTrue((hooks_dir / "post-commit").exists())

        skill_file = self.repo_dir / ".agents" / "skills" / "git-prompt-log" / "SKILL.md"
        self.assertFalse(skill_file.exists())

    def test_init_subcommand_with_skill(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init", "--skill"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        skill_file = self.repo_dir / ".agents" / "skills" / "git-prompt-log" / "SKILL.md"
        self.assertTrue(skill_file.exists())
        self.assertIn("git-prompt-log", skill_file.read_text(encoding="utf-8"))

    def test_init_migrates_legacy_hooks(self):
        hooks_dir = self.repo_dir / ".git" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        legacy_post_commit = hooks_dir / "post-commit"
        legacy_post_commit.write_text("#!/bin/sh\n# Git Prompt Note agent post-commit hook\ngit prompt-note post-commit --ref=\"refs/notes/commits\"\n")
        legacy_post_commit.chmod(0o755)

        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)
        content = legacy_post_commit.read_text(encoding="utf-8")
        self.assertIn("git prompt-log post-commit", content)
        self.assertNotIn("git prompt-note", content)

    def test_post_commit_silent_when_no_agent_env(self):
        sha = self._commit("file.txt", "content", "Manual commit")
        script_path = Path(gpn.__file__).resolve()
        # Run without AGY_SESSION_ID or ANTIGRAVITY_CONVERSATION_ID
        env = os.environ.copy()
        env.pop("AGY_SESSION_ID", None)
        env.pop("ANTIGRAVITY_CONVERSATION_ID", None)
        res = subprocess.run(
            ["python3", str(script_path), "post-commit"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
            env=env,
        )
        self.assertEqual(res.returncode, 0)
        # Should not attach any note to human commit
        self.assertIsNone(gpn.get_note_content(sha, repo_root=self.repo_dir))

    def test_init_defaults_to_no_skill(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        # 1. Hooks installed
        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertTrue(os.access(hooks_dir / "post-rewrite", os.X_OK))
        self.assertTrue((hooks_dir / "post-commit").exists())
        self.assertTrue(os.access(hooks_dir / "post-commit", os.X_OK))

        # 2. Local git config set
        cfg_res = subprocess.check_output(
            ["git", "config", "--local", "notes.rewriteRef"],
            cwd=self.repo_dir,
            text=True,
        ).strip()
        self.assertEqual(cfg_res, "refs/notes/commits")

        # 3. Local skill NOT installed by default
        skill_file = self.repo_dir / ".agents" / "skills" / "git-prompt-log" / "SKILL.md"
        self.assertFalse(skill_file.exists())

    def test_init_installs_skill_with_flag(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init", "--skill"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        skill_file = self.repo_dir / ".agents" / "skills" / "git-prompt-log" / "SKILL.md"
        self.assertTrue(skill_file.exists())
        self.assertIn("git-prompt-log", skill_file.read_text(encoding="utf-8"))

    def test_init_no_post_commit(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init", "--no-post-commit"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertFalse((hooks_dir / "post-commit").exists())

    def test_uninstall_hook_removes_both_hooks(self):
        script_path = Path(gpn.__file__).resolve()
        subprocess.run(["python3", str(script_path), "init"], cwd=self.repo_dir, check=True, capture_output=True)
        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertTrue((hooks_dir / "post-commit").exists())

        res = subprocess.run(["python3", str(script_path), "uninstall-hook"], cwd=self.repo_dir, capture_output=True, text=True)
        self.assertEqual(res.returncode, 0)
        self.assertFalse((hooks_dir / "post-rewrite").exists())
        self.assertFalse((hooks_dir / "post-commit").exists())

    def test_uninstall_hook_all(self):
        script_path = Path(gpn.__file__).resolve()
        subprocess.run(["python3", str(script_path), "init", "--skill"], cwd=self.repo_dir, check=True, capture_output=True)
        hooks_dir = self.repo_dir / ".git" / "hooks"
        skill_file = self.repo_dir / ".agents" / "skills" / "git-prompt-log" / "SKILL.md"
        self.assertTrue(skill_file.exists())

        res = subprocess.run(["python3", str(script_path), "uninstall-hook", "--all"], cwd=self.repo_dir, capture_output=True, text=True)
        self.assertEqual(res.returncode, 0)
        self.assertFalse((hooks_dir / "post-rewrite").exists())
        self.assertFalse((hooks_dir / "post-commit").exists())
        self.assertFalse(skill_file.exists())

        # Config should be unset
        res_cfg = subprocess.run(["git", "config", "--local", "notes.rewriteRef"], cwd=self.repo_dir, capture_output=True)
        self.assertNotEqual(res_cfg.returncode, 0)

    def test_uninstall_hook_preserves_other_commands(self):
        hooks_dir = self.repo_dir / ".git" / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)
        post_commit = hooks_dir / "post-commit"
        post_commit.write_text("#!/bin/sh\n# Custom hook\necho custom\n\n# Git Prompt Log agent post-commit hook\ngit prompt-log post-commit\n")
        post_commit.chmod(0o755)

        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(["python3", str(script_path), "uninstall-hook", "--post-commit-only"], cwd=self.repo_dir, capture_output=True, text=True)
        self.assertEqual(res.returncode, 0)
        self.assertTrue(post_commit.exists())
        content = post_commit.read_text()
        self.assertIn("echo custom", content)
        self.assertNotIn("git prompt-log", content)



class TestExportAndImportLog(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.repo_dir = Path(self.temp_dir.name)
        subprocess.run(["git", "init"], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=self.repo_dir, check=True)

    def tearDown(self):
        self.temp_dir.cleanup()

    def _commit(self, filename: str, content: str, msg: str) -> str:
        fpath = self.repo_dir / filename
        fpath.write_text(content)
        subprocess.run(["git", "add", filename], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "commit", "-m", msg], cwd=self.repo_dir, check=True, capture_output=True)
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()

    def test_export_and_import_exact(self):
        sha = self._commit("file1.txt", "v1", "feat: Feature one")
        note = gpn.SessionNote(
            session_id="session-export-1",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:00:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 00:59:00", "Build feature one")],
        )
        gpn.write_note_content(sha, note.format(), repo_root=self.repo_dir)

        # Export log
        out_file = self.repo_dir / "prompts" / "test_export.md"
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "export-log", "--output", str(out_file), "--range", "HEAD~1..HEAD"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)
        self.assertTrue(out_file.exists())
        log_content = out_file.read_text(encoding="utf-8")
        self.assertIn("# Prompt Log", log_content)
        self.assertIn("Build feature one", log_content)
        self.assertIn("<!-- git-prompt-log:metadata", log_content)

        # Remove note
        subprocess.run(["git", "notes", "remove", sha], cwd=self.repo_dir, check=True, capture_output=True)
        self.assertIsNone(gpn.get_note_content(sha, repo_root=self.repo_dir))

        # Import log back
        res_import = subprocess.run(
            ["python3", str(script_path), "import-log", str(out_file)],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res_import.returncode, 0)

        # Note restored
        restored = gpn.get_note_content(sha, repo_root=self.repo_dir)
        self.assertIsNotNone(restored)
        notes = gpn.parse_notes(restored)
        self.assertEqual(len(notes), 1)
        self.assertEqual(notes[0].session_id, "session-export-1")
        self.assertEqual(notes[0].prompts[0].text, "Build feature one")

    def test_import_legacy_metadata_format(self):
        sha = self._commit("file_legacy.txt", "legacy", "feat: Legacy Feature")
        # Legacy log format with <!-- git-prompt-note:metadata
        legacy_log = f"""# Prompt Log: Legacy

## Commit `{sha[:7]}` - feat: Legacy Feature

### Assistant Session: `session-legacy`
- **Harness:** Antigravity CLI 1.1.24
- **Model:** Gemini 3.8 Flash (High)
- **Recorded:** 2026-09-01 10:00:00 UTC

**Prompts:**
1. `[2026-09-01 09:50:00]` Legacy prompt

<!-- git-prompt-note:metadata
{{
  "version": 1,
  "commits": [
    {{
      "hash": "{sha}",
      "subject": "feat: Legacy Feature",
      "note": "Assistant-Session: session-legacy\\nAssistant-Harness: Antigravity CLI 1.1.24\\nAssistant-Model: Gemini 3.8 Flash (High)\\nAssistant-Recorded: 2026-09-01 10:00:00 UTC\\n\\nAssistant-Prompts:\\n  [2026-09-01 09:50:00] Legacy prompt"
    }}
  ]
}}
-->
"""
        out_file = self.repo_dir / "prompts" / "legacy.md"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(legacy_log, encoding="utf-8")
        script_path = Path(gpn.__file__).resolve()
        res_import = subprocess.run(
            ["python3", str(script_path), "import-log", str(out_file)],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res_import.returncode, 0)
        restored = gpn.get_note_content(sha, repo_root=self.repo_dir)
        self.assertIsNotNone(restored)
        notes = gpn.parse_notes(restored)
        self.assertEqual(len(notes), 1)
        self.assertEqual(notes[0].session_id, "session-legacy")

    def test_import_reconciles_squashed_commit(self):
        sha1 = self._commit("file1.txt", "v1", "feat: Target Feature")
        note = gpn.SessionNote(
            session_id="session-squash-import",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:00:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 00:59:00", "Steer feature")],
        )
        gpn.write_note_content(sha1, note.format(), repo_root=self.repo_dir)

        out_file = self.repo_dir / "prompts" / "feature.md"
        script_path = Path(gpn.__file__).resolve()
        subprocess.run(
            ["python3", str(script_path), "export-log", "--output", str(out_file)],
            cwd=self.repo_dir,
            check=True,
            capture_output=True,
        )

        # Simulate commit amendment with different hash but same subject
        subprocess.run(["git", "notes", "remove", sha1], cwd=self.repo_dir, check=True, capture_output=True)
        f = self.repo_dir / "file2.txt"
        f.write_text("v2")
        subprocess.run(["git", "add", "."], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "commit", "--amend", "-m", "feat: Target Feature"], cwd=self.repo_dir, check=True, capture_output=True)
        sha_squashed = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        self.assertNotEqual(sha1, sha_squashed)

        # Import log should reconcile sha_squashed by subject match
        res_import = subprocess.run(
            ["python3", str(script_path), "import-log", str(out_file)],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res_import.returncode, 0)
        reconciled = gpn.get_note_content(sha_squashed, repo_root=self.repo_dir)
        self.assertIsNotNone(reconciled)
        notes = gpn.parse_notes(reconciled)
        self.assertEqual(len(notes), 1)
        self.assertEqual(notes[0].prompts[0].text, "Steer feature")


class TestPromptExclusionAndRetraction(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.logs_dir = Path(self.temp_dir.name) / "brain" / "test-session-uuid" / ".system_generated" / "logs"
        self.logs_dir.mkdir(parents=True, exist_ok=True)
        self.transcript_file = self.logs_dir / "transcript.jsonl"

    def tearDown(self):
        self.temp_dir.cleanup()

    def _write_transcript(self, user_prompts: list):
        with open(self.transcript_file, "w", encoding="utf-8") as f:
            for i, p in enumerate(user_prompts):
                step = {
                    "type": "USER_INPUT",
                    "source": "USER_EXPLICIT",
                    "content": p,
                    "created_at": f"2026-09-04T09:{10+i:02d}:00Z",
                }
                f.write(json.dumps(step) + "\n")

    def test_ignore_prefix_excluded(self):
        self._write_transcript([
            "First valid prompt",
            "[ignore] Accidental prompt in wrong window",
            "[wrong-session] Meant for another project",
            "[skip] Temporary check",
            "(wrong session: oops)",
            "Second valid prompt",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Second valid prompt"])

    def test_retract_last_prompt(self):
        self._write_transcript([
            "First valid prompt",
            "Oops wrong window prompt",
            "[ignore-last]",
            "Second valid prompt",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Second valid prompt"])

    def test_retract_multiple_prompts(self):
        self._write_transcript([
            "First valid prompt",
            "Accident 1",
            "Accident 2",
            "[ignore-last 2]",
            "Second valid prompt",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Second valid prompt"])

    def test_standalone_wrong_session_retracts_last(self):
        self._write_transcript([
            "First valid prompt",
            "Accidental prompt for other repo",
            "[wrong-session]",
            "Second valid prompt",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Second valid prompt"])

    def test_retract_and_steer_in_one_turn(self):
        self._write_transcript([
            "Accidental prompt",
            "[ignore-last] Real intended prompt for this repository",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["Real intended prompt for this repository"])

    def test_ignore_all_resets_prompts(self):
        self._write_transcript([
            "Accident 1",
            "Accident 2",
            "[ignore-all]",
            "Fresh prompt",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["Fresh prompt"])

    def test_normal_english_sentences_preserved(self):
        self._write_transcript([
            "Ignore previous compiler warnings and proceed with build",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["Ignore previous compiler warnings and proceed with build"])

    def test_custom_exclusion_patterns(self):
        self._write_transcript([
            "Implement initial parser",
            "Commit",
            "Refactor AST node types",
            "commit changes please",
            "commit",
        ])
        # With custom pattern "^(?i)commit$" only standalone "Commit" / "commit" are ignored
        data = gpn.parse_session_transcript(self.transcript_file, custom_patterns=[r"^(?i)commit$"])
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, [
            "Implement initial parser",
            "Refactor AST node types",
            "commit changes please",
        ])

        # is_ignored_prompt check
        self.assertTrue(gpn.is_ignored_prompt("Commit", [r"^(?i)commit$"]))
        self.assertTrue(gpn.is_ignored_prompt("commit", [r"^(?i)commit$"]))
        self.assertFalse(gpn.is_ignored_prompt("Fix commit parser bug", [r"^(?i)commit$"]))

    def test_targeted_retraction_by_pattern(self):
        self._write_transcript([
            "First valid prompt",
            "Commit",
            "Second valid prompt",
            "[retract \"Commit\"]",
            "Third valid prompt",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Second valid prompt", "Third valid prompt"])

    def test_targeted_retraction_by_index(self):
        self._write_transcript([
            "First valid prompt",
            "Accidental prompt at index 2",
            "Third valid prompt",
            "[drop-prompt 2]",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Third valid prompt"])

    def test_targeted_retraction_and_steer(self):
        self._write_transcript([
            "First valid prompt",
            "Accidental query",
            "[retract 'Accidental query'] Next intended feature",
        ])
        data = gpn.parse_session_transcript(self.transcript_file)
        self.assertIsNotNone(data)
        prompts = [p.text for p in data["prompts"]]
        self.assertEqual(prompts, ["First valid prompt", "Next intended feature"])


class TestWorkflowAndAttributionLifecycle(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.TemporaryDirectory()
        self.repo_dir = Path(self.tmp_dir.name) / "repo"
        self.repo_dir.mkdir()
        self.data_dir = Path(self.tmp_dir.name) / "data"
        self.data_dir.mkdir()

        # Set up git repo
        subprocess.run(["git", "init", "-b", "main"], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=self.repo_dir, check=True)

        # Initialize git-prompt-log hooks
        script_path = Path(gpn.__file__).resolve()
        subprocess.run(["python3", str(script_path), "init"], cwd=self.repo_dir, check=True, capture_output=True)

        # Set up mock transcript
        self.session_id = "test-workflow-session-1234"
        self.logs_dir = self.data_dir / "brain" / self.session_id / ".system_generated" / "logs"
        self.logs_dir.mkdir(parents=True, exist_ok=True)
        self.transcript_file = self.logs_dir / "transcript.jsonl"

        # Prepare env with local bin directory at the head of PATH
        self.env = os.environ.copy()
        self.env["PATH"] = f"{bin_path.parent}:{self.env.get('PATH', '')}"
        self.env["ANTIGRAVITY_DATA_DIR"] = str(self.data_dir)
        self.env["ANTIGRAVITY_CONVERSATION_ID"] = self.session_id

    def tearDown(self):
        self.tmp_dir.cleanup()

    def _append_prompt(self, text: str, timestamp_str: str):
        step = {
            "type": "USER_INPUT",
            "source": "USER_EXPLICIT",
            "content": text,
            "created_at": timestamp_str,
        }
        with open(self.transcript_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(step) + "\n")

    def _commit(self, filename: str, content: str, msg: str) -> str:
        fpath = self.repo_dir / filename
        fpath.write_text(content)
        subprocess.run(["git", "add", filename], cwd=self.repo_dir, check=True, capture_output=True, env=self.env)
        subprocess.run(["git", "commit", "-m", msg], cwd=self.repo_dir, check=True, capture_output=True, env=self.env)
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True, env=self.env).strip()

    def test_sequential_commits_cumulative_history(self):
        # 1. First prompt and commit
        self._append_prompt("Implement feature part 1", "2026-09-04T10:00:00Z")
        sha1 = self._commit("file1.txt", "v1", "feat: Feature part 1")

        note1_raw = gpn.get_note_content(sha1, repo_root=self.repo_dir)
        self.assertIsNotNone(note1_raw)
        notes1 = gpn.parse_notes(note1_raw)
        self.assertEqual(len(notes1), 1)
        self.assertEqual(len(notes1[0].prompts), 1)
        self.assertEqual(notes1[0].prompts[0].text, "Implement feature part 1")

        # 2. Second prompt and commit
        self._append_prompt("Implement feature part 2", "2026-09-04T10:05:00Z")
        sha2 = self._commit("file2.txt", "v2", "feat: Feature part 2")

        # Commit 2 carries full cumulative history (Prompt 1 + Prompt 2)
        note2_raw = gpn.get_note_content(sha2, repo_root=self.repo_dir)
        self.assertIsNotNone(note2_raw)
        notes2 = gpn.parse_notes(note2_raw)
        # Commit 2 carries full cumulative history (Prompt 2 causal at top, Prompt 1 below)
        note2_raw = gpn.get_note_content(sha2, repo_root=self.repo_dir)
        self.assertIsNotNone(note2_raw)
        notes2 = gpn.parse_notes(note2_raw)
        self.assertEqual(len(notes2), 1)
        self.assertEqual(len(notes2[0].prompts), 2)
        self.assertEqual(notes2[0].prompts[0].text, "Implement feature part 2")
        self.assertEqual(notes2[0].prompts[1].text, "Implement feature part 1")

        # Commit 1 still retains its original snapshot
        note1_check = gpn.get_note_content(sha1, repo_root=self.repo_dir)
        self.assertEqual(note1_check, note1_raw)

        # Verify show --active and show --incremental
        out_active = subprocess.check_output(
            ["python3", str(Path(gpn.__file__).resolve()), "show", "--active", sha2],
            cwd=self.repo_dir,
            text=True,
            env=self.env,
        ).strip()
        self.assertEqual(out_active, "[2026-09-04 10:05:00 UTC] Implement feature part 2")

        out_inc = subprocess.check_output(
            ["python3", str(Path(gpn.__file__).resolve()), "show", "--incremental", sha2],
            cwd=self.repo_dir,
            text=True,
            env=self.env,
        ).strip()
        self.assertEqual(out_inc, "[2026-09-04 10:05:00 UTC] Implement feature part 2")

    def test_commit_amend_carries_and_merges_note(self):
        self._append_prompt("Initial commit prompt", "2026-09-04T10:00:00Z")
        sha1 = self._commit("file1.txt", "v1", "feat: Original")

        # Now add a followup prompt before amending
        self._append_prompt("Improve performance on feature", "2026-09-04T10:05:00Z")
        fpath = self.repo_dir / "file1.txt"
        fpath.write_text("v2")
        subprocess.run(["git", "add", "file1.txt"], cwd=self.repo_dir, check=True, env=self.env)
        subprocess.run(["git", "commit", "--amend", "-m", "feat: Original improved"], cwd=self.repo_dir, check=True, env=self.env)

        sha_amended = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        self.assertNotEqual(sha1, sha_amended)

        note_amended_raw = gpn.get_note_content(sha_amended, repo_root=self.repo_dir)
        self.assertIsNotNone(note_amended_raw)
        notes = gpn.parse_notes(note_amended_raw)
        self.assertEqual(len(notes), 1)
        self.assertEqual(len(notes[0].prompts), 2)
        self.assertEqual(notes[0].prompts[0].text, "Improve performance on feature")
        self.assertEqual(notes[0].prompts[1].text, "Initial commit prompt")

    def test_native_git_rebase_squash(self):
        # Base commit
        self._commit("base.txt", "base", "chore: Base commit")

        # Commit 1
        self._append_prompt("Build part A", "2026-09-04T10:00:00Z")
        sha1 = self._commit("a.txt", "a", "feat: Part A")

        # Commit 2
        self._append_prompt("Build part B", "2026-09-04T10:05:00Z")
        sha2 = self._commit("b.txt", "b", "feat: Part B")

        # Interactive squash of HEAD into HEAD~1
        # Set GIT_SEQUENCE_EDITOR to change 2nd 'pick' to 'squash'
        py_editor = "python3 -c 'import sys; p=sys.argv[1]; lines=open(p).readlines(); lines[1]=\"squash \" + lines[1].split(\" \", 1)[1]; open(p,\"w\").writelines(lines)'"
        env = self.env.copy()
        env["GIT_SEQUENCE_EDITOR"] = py_editor
        env["GIT_EDITOR"] = "true"  # for commit message editor
        subprocess.run(["git", "rebase", "-i", "HEAD~2"], cwd=self.repo_dir, check=True, env=env)

        sha_squashed = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        note_raw = gpn.get_note_content(sha_squashed, repo_root=self.repo_dir)
        self.assertIsNotNone(note_raw)
        notes = gpn.parse_notes(note_raw)
        self.assertEqual(len(notes), 1)
        self.assertEqual(len(notes[0].prompts), 2)
        self.assertEqual(notes[0].prompts[0].text, "Build part B")
        self.assertEqual(notes[0].prompts[1].text, "Build part A")

    def test_native_git_rebase_onto_upstream(self):
        # Base commit
        self._append_prompt("Base commit", "2026-09-04T09:50:00Z")
        sha_base = self._commit("base.txt", "base", "chore: Base")

        # Feature branch
        subprocess.run(["git", "checkout", "-b", "feature"], cwd=self.repo_dir, check=True, env=self.env)
        self._append_prompt("Feature work", "2026-09-04T10:00:00Z")
        sha_feat = self._commit("feat.txt", "feat", "feat: Feature")

        # Switch to main and add upstream commit
        subprocess.run(["git", "checkout", "main"], cwd=self.repo_dir, check=True, env=self.env)
        self._append_prompt("Upstream work", "2026-09-04T10:05:00Z")
        sha_upstream = self._commit("upstream.txt", "upstream", "chore: Upstream")

        # Switch back to feature and rebase onto main
        subprocess.run(["git", "checkout", "feature"], cwd=self.repo_dir, check=True, env=self.env)
        subprocess.run(["git", "rebase", "main"], cwd=self.repo_dir, check=True, env=self.env)

        # Rebased feature commit should have a new hash but retain its prompt note!
        sha_rebased = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        self.assertNotEqual(sha_feat, sha_rebased)

        note_raw = gpn.get_note_content(sha_rebased, repo_root=self.repo_dir)
        self.assertIsNotNone(note_raw)
        notes = gpn.parse_notes(note_raw)
        self.assertEqual(len(notes[0].prompts), 2)
        self.assertEqual(notes[0].prompts[0].text, "Feature work")
        self.assertEqual(notes[0].prompts[1].text, "Base commit")

    def test_rebase_drop_narrative_lands_on_replacement_commit(self):
        # 1. Base commit
        self._commit("base.txt", "base", "chore: Base commit")

        # 2. First feature commit
        self._append_prompt("Implement basic audio engine", "2026-09-04T10:05:00Z")
        sha1 = self._commit("audio.c", "audio", "audio: Implement basic audio engine")

        # 3. Dead-end feature commit
        self._append_prompt("Try implementing custom Doppler shift calculation in audio update loop", "2026-09-04T10:10:00Z")
        sha2_dead_end = self._commit("doppler.c", "doppler", "audio: Add custom Doppler calculation")

        # 4. User redirects: drop Doppler commit
        self._append_prompt("The custom Doppler math is causing distortion. Drop that commit and use OpenAL distance attenuation instead", "2026-09-04T10:15:00Z")

        # Drop sha2 via interactive rebase
        drop_py = "python3 -c 'import sys; p=sys.argv[1]; lines=open(p).readlines(); lines[1]=\"drop \" + lines[1].split(\" \", 1)[1]; open(p,\"w\").writelines(lines)'"
        env = self.env.copy()
        env["GIT_SEQUENCE_EDITOR"] = drop_py
        subprocess.run(["git", "rebase", "-i", "HEAD~2"], cwd=self.repo_dir, check=True, env=env)

        # 5. Replacement commit authored
        sha3 = self._commit("openal.c", "openal", "audio: Configure OpenAL distance attenuation")

        # Verify sha1 has ONLY prompt 1
        note1_raw = gpn.get_note_content(sha1, repo_root=self.repo_dir)
        notes1 = gpn.parse_notes(note1_raw)
        self.assertEqual(len(notes1[0].prompts), 1)
        self.assertEqual(notes1[0].prompts[0].text, "Implement basic audio engine")

        # Replacement commit sha3 retains full cumulative lineage with newest causal prompt at top!
        note3_raw = gpn.get_note_content(sha3, repo_root=self.repo_dir)
        self.assertIsNotNone(note3_raw)
        notes3 = gpn.parse_notes(note3_raw)
        self.assertEqual(len(notes3[0].prompts), 3)
        self.assertEqual(notes3[0].prompts[0].text, "The custom Doppler math is causing distortion. Drop that commit and use OpenAL distance attenuation instead")
        self.assertEqual(notes3[0].prompts[1].text, "Try implementing custom Doppler shift calculation in audio update loop")
        self.assertEqual(notes3[0].prompts[2].text, "Implement basic audio engine")

    def test_rebase_reorder_commits_preserves_notes_without_duplication(self):
        # 1. Base commit
        self._commit("base.txt", "base", "chore: Base")

        # 2. Commit A
        self._append_prompt("Feature A (Sound)", "2026-09-04T10:05:00Z")
        sha_a = self._commit("sound.txt", "sound", "feat: Sound")

        # 3. Commit B
        self._append_prompt("Feature B (Music)", "2026-09-04T10:10:00Z")
        sha_b = self._commit("music.txt", "music", "feat: Music")

        # Reorder commits so B is applied before A
        reorder_py = "python3 -c 'import sys; p=sys.argv[1]; lines=open(p).readlines(); lines[0], lines[1] = lines[1], lines[0]; open(p,\"w\").writelines(lines)'"
        env = self.env.copy()
        env["GIT_SEQUENCE_EDITOR"] = reorder_py
        subprocess.run(["git", "rebase", "-i", "HEAD~2"], cwd=self.repo_dir, check=True, env=env)

        # Retrieve new commit hashes in reordered history (HEAD is A, HEAD~1 is B)
        new_sha_a = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        new_sha_b = subprocess.check_output(["git", "rev-parse", "HEAD~1"], cwd=self.repo_dir, text=True).strip()

        # Both reordered commits retain their respective notes
        note_a = gpn.parse_notes(gpn.get_note_content(new_sha_a, repo_root=self.repo_dir))[0]
        note_b = gpn.parse_notes(gpn.get_note_content(new_sha_b, repo_root=self.repo_dir))[0]
        self.assertEqual(len(note_a.prompts), 1)
        self.assertEqual(note_a.prompts[0].text, "Feature A (Sound)")
        self.assertEqual(len(note_b.prompts), 2)
        self.assertEqual(note_b.prompts[0].text, "Feature B (Music)")
        self.assertEqual(note_b.prompts[1].text, "Feature A (Sound)")

        # 4. Author a subsequent commit C in the same session
        self._append_prompt("Feature C (UI)", "2026-09-04T10:15:00Z")
        sha_c = self._commit("ui.txt", "ui", "feat: UI")

        # Commit C receives all prompts up to its creation (newest causal at top)
        note_c = gpn.parse_notes(gpn.get_note_content(sha_c, repo_root=self.repo_dir))[0]
        self.assertEqual(len(note_c.prompts), 3)
        self.assertEqual(note_c.prompts[0].text, "Feature C (UI)")

    def test_git_reset_recommit_preserves_cumulative_history(self):
        # 1. Base commit
        self._commit("base.txt", "base", "chore: Base commit")

        # 2. Turn 1
        self._append_prompt("First attempt at parser", "2026-09-04T10:00:00Z")
        sha1 = self._commit("p.txt", "parser", "feat: Parser")

        # 3. Turn 2
        self._append_prompt("First attempt at AST", "2026-09-04T10:05:00Z")
        sha2 = self._commit("a.txt", "ast", "feat: AST")

        # 4. Turn 3: Agent does a hard/soft reset to clean up and re-split
        self._append_prompt("Reset and re-split cleanly into tokens and parser", "2026-09-04T10:10:00Z")
        subprocess.run(["git", "reset", "--soft", "HEAD~2"], cwd=self.repo_dir, check=True)

        # Author replacement commits
        sha_new1 = self._commit("tokens.txt", "tokens", "feat: Tokens")
        sha_new2 = self._commit("parser.txt", "parser_clean", "feat: Clean Parser")

        # Both replacement commits must preserve the full session history with causal prompt at top!
        note_new1 = gpn.parse_notes(gpn.get_note_content(sha_new1, repo_root=self.repo_dir))[0]
        note_new2 = gpn.parse_notes(gpn.get_note_content(sha_new2, repo_root=self.repo_dir))[0]

        self.assertEqual(len(note_new1.prompts), 3)
        self.assertEqual(note_new1.prompts[0].text, "Reset and re-split cleanly into tokens and parser")
        self.assertEqual(note_new1.prompts[1].text, "First attempt at AST")
        self.assertEqual(note_new1.prompts[2].text, "First attempt at parser")

        self.assertEqual(len(note_new2.prompts), 3)
        self.assertEqual(note_new2.prompts[0].text, "Reset and re-split cleanly into tokens and parser")

        # Log command displays cleanly
        out_log = subprocess.check_output(
            ["python3", str(Path(gpn.__file__).resolve()), "log", "--no-pager"],
            cwd=self.repo_dir,
            text=True,
            env=self.env,
        )
        self.assertIn("feat: Clean Parser", out_log)
        self.assertIn("Reset and re-split cleanly into tokens and parser", out_log)

        # Verify color formatting in log
        out_color = subprocess.check_output(
            ["python3", str(Path(gpn.__file__).resolve()), "log", "--color=always", "--no-pager"],
            cwd=self.repo_dir,
            text=True,
            env=self.env,
        )
        self.assertIn("\033[33m", out_color)
        self.assertIn("\033[36m", out_color)
        self.assertIn("\033[0m", out_color)

        out_no_color = subprocess.check_output(
            ["python3", str(Path(gpn.__file__).resolve()), "log", "--color=never", "--no-pager"],
            cwd=self.repo_dir,
            text=True,
            env=self.env,
        )
        self.assertNotIn("\033[33m", out_no_color)
        self.assertNotIn("\033[36m", out_no_color)

    def test_always_skip_configured_exclude_pattern_and_retroactive_drop(self):
        # 1. Configure git exclude pattern
        subprocess.run(["git", "config", "--add", "prompt-log.exclude", r"^(?i)commit$"], cwd=self.repo_dir, check=True)
        patterns = gpn.get_configured_exclude_patterns(self.repo_dir)
        self.assertIn(r"^(?i)commit$", patterns)

        # 2. Append real prompt followed by routine "Commit" prompt
        self._append_prompt("Implement user authentication", "2026-09-04T10:00:00Z")
        self._append_prompt("Commit", "2026-09-04T10:01:00Z")
        sha1 = self._commit("auth.py", "def login(): pass", "feat: Add login")

        # 3. Post-commit hook recorded note: verify "Commit" was automatically skipped
        raw1 = gpn.get_note_content(sha1, repo_root=self.repo_dir)
        self.assertIsNotNone(raw1)
        notes1 = gpn.parse_notes(raw1)
        self.assertEqual(len(notes1), 1)
        prompts1 = [p.text for p in notes1[0].prompts]
        self.assertEqual(prompts1, ["Implement user authentication"])

        # 4. Append next prompt followed by another routine "commit"
        self._append_prompt("Add unit tests for auth", "2026-09-04T10:05:00Z")
        self._append_prompt("commit", "2026-09-04T10:06:00Z")
        sha2 = self._commit("test_auth.py", "def test_login(): pass", "test: Add auth tests")

        raw2 = gpn.get_note_content(sha2, repo_root=self.repo_dir)
        self.assertIsNotNone(raw2)
        notes2 = gpn.parse_notes(raw2)
        prompts2 = [p.text for p in notes2[0].prompts]
        # Cumulative history contains both feature prompts, neither "Commit" prompt
        self.assertEqual(prompts2, ["Add unit tests for auth", "Implement user authentication"])

        # 5. Test CLI retroactive drop on existing commit notes:
        # Purge "Add unit tests for auth" from sha2 note using git prompt-log record --drop
        cmd = ["python3", str(Path(gpn.__file__).resolve()), "record", "--commit", sha2, "--drop", r"Add unit tests"]
        subprocess.run(cmd, cwd=self.repo_dir, check=True, env=self.env)

        raw2_updated = gpn.get_note_content(sha2, repo_root=self.repo_dir)
        notes2_updated = gpn.parse_notes(raw2_updated)
        prompts2_updated = [p.text for p in notes2_updated[0].prompts]
        self.assertEqual(prompts2_updated, ["Implement user authentication"])

        # 6. Test uninstall-hook --all cleans prompt-log.exclude
        uninstall_cmd = ["python3", str(Path(gpn.__file__).resolve()), "uninstall-hook", "--all"]
        subprocess.run(uninstall_cmd, cwd=self.repo_dir, check=True)
        patterns_after = gpn.get_configured_exclude_patterns(self.repo_dir)
        self.assertEqual(patterns_after, [])

    def test_session_drop_and_undrop_cli(self):
        # 1. Author initial commit with two prompts
        self._append_prompt("Initial architecture plan", "2026-09-04T12:00:00Z")
        self._append_prompt("Accidental query about unrelated project", "2026-09-04T12:05:00Z")
        sha1 = self._commit("arch.txt", "arch", "feat: Arch")

        raw1 = gpn.get_note_content(sha1, repo_root=self.repo_dir)
        notes1 = gpn.parse_notes(raw1)
        self.assertEqual(len(notes1[0].prompts), 2)

        # 2. Drop prompt #2 specifically from this session via CLI
        cmd_drop = [
            "python3",
            str(Path(gpn.__file__).resolve()),
            "session",
            "drop",
            "2",
        ]
        subprocess.run(cmd_drop, cwd=self.repo_dir, check=True, env=self.env)

        # Note on HEAD (sha1) was automatically updated!
        raw1_after = gpn.get_note_content(sha1, repo_root=self.repo_dir)
        notes1_after = gpn.parse_notes(raw1_after)
        prompts1_after = [p.text for p in notes1_after[0].prompts]
        self.assertEqual(prompts1_after, ["Initial architecture plan"])

        # 3. Add subsequent prompt and make new commit:
        # Verify that new commit created by post-commit hook also omits prompt #2!
        self._append_prompt("Implement data layer", "2026-09-04T12:10:00Z")
        sha2 = self._commit("data.txt", "data", "feat: Data layer")

        raw2 = gpn.get_note_content(sha2, repo_root=self.repo_dir)
        notes2 = gpn.parse_notes(raw2)
        prompts2 = [p.text for p in notes2[0].prompts]
        self.assertEqual(prompts2, ["Implement data layer", "Initial architecture plan"])

        # 4. Restore prompt #2 via session undrop
        cmd_undrop = [
            "python3",
            str(Path(gpn.__file__).resolve()),
            "session",
            "undrop",
            "2",
        ]
        subprocess.run(cmd_undrop, cwd=self.repo_dir, check=True, env=self.env)

        raw2_undropped = gpn.get_note_content(sha2, repo_root=self.repo_dir)
        notes2_undropped = gpn.parse_notes(raw2_undropped)
        prompts2_undropped = [p.text for p in notes2_undropped[0].prompts]
        self.assertEqual(len(prompts2_undropped), 3)
        self.assertIn("Accidental query about unrelated project", prompts2_undropped)

        # 5. Verify exclusion filename has no leading dot in session dir
        brain_session_dir = self.data_dir / "brain" / self.session_id
        excludes_file = brain_session_dir / "prompt-log-excludes.json"
        legacy_file = brain_session_dir / ".prompt-log-excludes.json"
        self.assertTrue(excludes_file.exists())
        self.assertFalse(legacy_file.exists())

    def test_legacy_dot_excludes_file_migration(self):
        legacy_session = "legacy-session-9876"
        session_dir = self.data_dir / "brain" / legacy_session
        session_dir.mkdir(parents=True, exist_ok=True)
        legacy_file = session_dir / ".prompt-log-excludes.json"
        legacy_file.write_text(json.dumps({"patterns": ["legacy_pattern"], "indices": [], "timestamps": []}))

        orig_dir = os.environ.get("ANTIGRAVITY_DATA_DIR")
        os.environ["ANTIGRAVITY_DATA_DIR"] = str(self.data_dir)
        try:
            # Loading reads legacy file
            loaded = gpn.load_session_excludes(legacy_session)
            self.assertEqual(loaded["patterns"], ["legacy_pattern"])

            # Saving writes non-hidden file and cleans up legacy file
            loaded["patterns"].append("new_pattern")
            gpn.save_session_excludes(legacy_session, loaded)

            new_file = session_dir / "prompt-log-excludes.json"
            self.assertTrue(new_file.exists())
            self.assertFalse(legacy_file.exists())
            migrated = json.loads(new_file.read_text(encoding="utf-8"))
            self.assertIn("legacy_pattern", migrated["patterns"])
            self.assertIn("new_pattern", migrated["patterns"])
        finally:
            if orig_dir is not None:
                os.environ["ANTIGRAVITY_DATA_DIR"] = orig_dir
            else:
                os.environ.pop("ANTIGRAVITY_DATA_DIR", None)


class TestIngestionAdapters(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.work_dir = Path(self.temp_dir.name)

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_registry_listing_and_lookup(self):
        adapters = gpn.REGISTRY.list_adapters()
        names = [a.name for a in adapters]
        self.assertIn("antigravity", names)
        self.assertIn("claude", names)
        self.assertIn("manual", names)

        self.assertIsInstance(gpn.REGISTRY.get("antigravity"), gpn.AntigravityAdapter)
        self.assertIsInstance(gpn.REGISTRY.get("claude"), gpn.ClaudeCodeAdapter)
        self.assertIsInstance(gpn.REGISTRY.get("manual"), gpn.ManualAdapter)
        self.assertIsInstance(gpn.REGISTRY.get("direct"), gpn.ManualAdapter)

    def test_claude_adapter_parsing_jsonl(self):
        transcript = self.work_dir / "claude-session.jsonl"
        lines = [
            json.dumps({"type": "user", "message": {"content": "Build ingestion adapter"}, "timestamp": "2026-09-04T12:00:00Z"}),
            json.dumps({"type": "assistant", "message": {"model": "claude-3-7-sonnet"}}),
            json.dumps({"type": "user", "message": {"content": "[ignore] accidental prompt"}, "timestamp": "2026-09-04T12:01:00Z"}),
            json.dumps({"type": "user", "message": {"content": "Add unit tests"}, "timestamp": "2026-09-04T12:02:00Z"}),
        ]
        transcript.write_text("\n".join(lines), encoding="utf-8")

        adapter = gpn.ClaudeCodeAdapter()
        parsed = adapter.parse_transcript_file(transcript)
        self.assertIsNotNone(parsed)
        self.assertEqual(parsed["detected_model"], "claude-3-7-sonnet")
        prompts = [p.text for p in parsed["prompts"]]
        self.assertEqual(prompts, ["Build ingestion adapter", "Add unit tests"])

    def test_claude_adapter_parsing_json_array(self):
        transcript = self.work_dir / "session.json"
        data = [
            {"role": "user", "content": [{"type": "text", "text": "First user message"}], "timestamp": "2026-09-04T10:00:00Z", "model": "claude-3-5-haiku"},
            {"role": "assistant", "content": "Sure, here is the answer."},
            {"role": "user", "content": "Second user message", "timestamp": "2026-09-04T10:05:00Z"},
        ]
        transcript.write_text(json.dumps(data), encoding="utf-8")

        adapter = gpn.ClaudeCodeAdapter()
        parsed = adapter.parse_transcript_file(transcript)
        self.assertIsNotNone(parsed)
        self.assertEqual(parsed["detected_model"], "claude-3-5-haiku")
        prompts = [p.text for p in parsed["prompts"]]
        self.assertEqual(prompts, ["First user message", "Second user message"])

    def test_manual_adapter_recording(self):
        adapter = gpn.ManualAdapter()
        parsed = adapter.find_session_data(
            session_id="manual-test-session",
            extra_options={"message": "Manual steer without transcript file"},
        )
        self.assertIsNotNone(parsed)
        self.assertEqual(parsed["session_id"], "manual-test-session")
        self.assertEqual(parsed["harness"], "Manual")
        self.assertEqual(len(parsed["prompts"]), 1)
        self.assertEqual(parsed["prompts"][0].text, "Manual steer without transcript file")

    def test_manual_record_cli_and_harness_subcommand(self):
        repo_dir = self.work_dir / "test_repo"
        repo_dir.mkdir()
        subprocess.run(["git", "init", "-b", "main"], cwd=repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo_dir, check=True)

        # Commit a file
        f = repo_dir / "hello.py"
        f.write_text("print('hello')")
        subprocess.run(["git", "add", "hello.py"], cwd=repo_dir, check=True)
        subprocess.run(["git", "commit", "-m", "Initial commit"], cwd=repo_dir, check=True)

        script_path = str(bin_path)

        # 1. Run harness --json subcommand
        res = subprocess.run(["python3", script_path, "harness", "--json"], cwd=repo_dir, capture_output=True, text=True, check=True)
        data = json.loads(res.stdout)
        self.assertIn("harnesses", data)
        adapter_names = [a["name"] for a in data["harnesses"]]
        self.assertIn("manual", adapter_names)
        self.assertIn("claude", adapter_names)

        # 2. Record manual prompt with -m and custom harness/model
        cmd_rec = [
            "python3",
            script_path,
            "record",
            "-m",
            "Initial prompt from developer",
            "--harness",
            "Human Dev",
            "--model",
            "Custom Mind",
            "-c",
            "HEAD",
        ]
        subprocess.run(cmd_rec, cwd=repo_dir, check=True, capture_output=True)

        note_content = gpn.get_note_content("HEAD", repo_root=repo_dir)
        self.assertIsNotNone(note_content)
        self.assertIn("Assistant-Harness: Human Dev", note_content)
        self.assertIn("Assistant-Model: Custom Mind", note_content)
        self.assertIn("Initial prompt from developer", note_content)

        # 3. Explicit record using --harness claude
        c_file = repo_dir / "claude_hist.jsonl"
        c_file.write_text(json.dumps({"role": "user", "content": "Explicit claude steer", "timestamp": "2026-09-04T18:00:00Z"}) + "\n", encoding="utf-8")
        c_env = os.environ.copy()
        c_env["CLAUDE_SESSION_ID"] = "sess-c-456"
        c_env["CLAUDE_TRANSCRIPT_PATH"] = str(c_file)
        subprocess.run(["python3", script_path, "record", "--harness", "claude", "-c", "HEAD"], cwd=repo_dir, env=c_env, check=True, capture_output=True)
        note_claude = gpn.get_note_content("HEAD", repo_root=repo_dir)
        self.assertIn("Assistant-Harness: Claude Code", note_claude)
        self.assertIn("Explicit claude steer", note_claude)

    def test_post_commit_causality_guard_and_claude_hook(self):
        repo_dir = self.work_dir / "repo_claude"
        repo_dir.mkdir()
        subprocess.run(["git", "init", "-b", "main"], cwd=repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo_dir, check=True)

        script_path = str(bin_path)
        subprocess.run(["python3", script_path, "init"], cwd=repo_dir, check=True, capture_output=True)

        # 1. Plain human commit without any agent environment variables
        f1 = repo_dir / "human.txt"
        f1.write_text("human")
        subprocess.run(["git", "add", "human.txt"], cwd=repo_dir, check=True)
        clean_env = os.environ.copy()
        for k in list(clean_env.keys()):
            if "AGY" in k or "ANTIGRAVITY" in k or "CLAUDE" in k or "AIDER" in k:
                del clean_env[k]
        clean_env["PATH"] = f"{bin_path.parent}:{clean_env.get('PATH', '')}"

        subprocess.run(["git", "commit", "-m", "Human commit"], cwd=repo_dir, env=clean_env, check=True)
        self.assertIsNone(gpn.get_note_content("HEAD", repo_root=repo_dir))

        # 2. Commit made within Claude Code session
        claude_transcript = repo_dir / ".claude" / "history.jsonl"
        claude_transcript.parent.mkdir(parents=True, exist_ok=True)
        claude_transcript.write_text(
            json.dumps({"role": "user", "content": "Refactor auth pipeline", "timestamp": "2026-09-04T18:00:00Z", "model": "claude-3-7-sonnet"}) + "\n",
            encoding="utf-8",
        )

        claude_env = clean_env.copy()
        claude_env["CLAUDE_SESSION_ID"] = "claude-session-999"
        claude_env["CLAUDE_TRANSCRIPT_PATH"] = str(claude_transcript)

        f2 = repo_dir / "auth.txt"
        f2.write_text("auth refactored")
        subprocess.run(["git", "add", "auth.txt"], cwd=repo_dir, check=True)
        subprocess.run(["git", "commit", "-m", "feat: Refactor auth"], cwd=repo_dir, env=claude_env, check=True)

        note = gpn.get_note_content("HEAD", repo_root=repo_dir)
        self.assertIsNotNone(note)
        self.assertIn("Assistant-Harness: Claude Code", note)
        self.assertIn("Assistant-Model: claude-3-7-sonnet", note)
        self.assertIn("Refactor auth pipeline", note)

    def test_harness_cli_and_git_config(self):
        repo_dir = self.work_dir / "repo_harness"
        repo_dir.mkdir()
        subprocess.run(["git", "init", "-b", "main"], cwd=repo_dir, check=True, capture_output=True)
        script_path = str(bin_path)

        # 1. Initially unconfigured
        res = subprocess.run(["python3", script_path, "harness"], cwd=repo_dir, capture_output=True, text=True, check=True)
        self.assertIn("Configured Harness: None", res.stdout)

        # 2. Set harness via CLI
        subprocess.run(["python3", script_path, "harness", "claude"], cwd=repo_dir, check=True, capture_output=True)
        res = subprocess.run(["python3", script_path, "harness"], cwd=repo_dir, capture_output=True, text=True, check=True)
        self.assertIn("Configured Harness: claude", res.stdout)

        # Verify git config prompt-log.harness was set
        conf = subprocess.check_output(["git", "config", "prompt-log.harness"], cwd=repo_dir, text=True).strip()
        self.assertEqual(conf, "claude")

        # 3. harness --json shows configured
        res = subprocess.run(["python3", script_path, "harness", "--json"], cwd=repo_dir, capture_output=True, text=True, check=True)
        data = json.loads(res.stdout)
        self.assertEqual(data["configured"], "claude")
        self.assertEqual(data["active"], "claude")

        # 4. Clear harness
        subprocess.run(["python3", script_path, "harness", "clear"], cwd=repo_dir, check=True, capture_output=True)
        res = subprocess.run(["python3", script_path, "harness"], cwd=repo_dir, capture_output=True, text=True, check=True)
        self.assertIn("Configured Harness: None", res.stdout)

        # 5. Environment variable override via PROMPT_LOG_HARNESS
        test_env = os.environ.copy()
        test_env["PROMPT_LOG_HARNESS"] = "antigravity"
        res = subprocess.run(["python3", script_path, "harness"], cwd=repo_dir, env=test_env, capture_output=True, text=True, check=True)
        self.assertIn("Configured Harness: antigravity", res.stdout)

    def test_init_with_harness_flag(self):
        repo_dir = self.work_dir / "repo_init_adapter"
        repo_dir.mkdir()
        subprocess.run(["git", "init", "-b", "main"], cwd=repo_dir, check=True, capture_output=True)
        script_path = str(bin_path)

        # Run init with --harness antigravity
        subprocess.run(["python3", script_path, "init", "--harness", "antigravity"], cwd=repo_dir, check=True, capture_output=True)
        conf = subprocess.check_output(["git", "config", "prompt-log.harness"], cwd=repo_dir, text=True).strip()
        self.assertEqual(conf, "antigravity")

        # Verify uninstall-hook --all clears it
        subprocess.run(["python3", script_path, "uninstall-hook", "--all"], cwd=repo_dir, check=True, capture_output=True)
        res = subprocess.run(["git", "config", "prompt-log.harness"], cwd=repo_dir, capture_output=True)
        self.assertNotEqual(res.returncode, 0)


if __name__ == "__main__":
    unittest.main()
