#!/usr/bin/env python3
# Generated by Antigravity CLI 1.1.25 (Gemini 3.8 Flash (High))
"""
Unit and integration tests for git_prompt_note.py.
"""

import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

import importlib.machinery
from pathlib import Path
bin_path = Path(__file__).resolve().parent.parent / "bin" / "git-prompt-note"
gpn = importlib.machinery.SourceFileLoader("git_prompt_note", str(bin_path)).load_module()


class TestNoteParsingAndFormatting(unittest.TestCase):
    def test_single_session_parse_and_format(self):
        raw = """Assistant-Session: 9674eda6-390f-4b1d-9910-72bec1843401
Assistant-Harness: Antigravity CLI 1.1.25
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-04 01:03:57 UTC

Assistant-Prompts:
  [2026-09-04 01:03:57] Make the camera pivot around the ball origin
  [2026-09-04 01:09:25]
    Let's implement this.
    Second line of prompt.
"""
        notes = gpn.parse_notes(raw)
        self.assertEqual(len(notes), 1)
        n = notes[0]
        self.assertEqual(n.session_id, "9674eda6-390f-4b1d-9910-72bec1843401")
        self.assertEqual(n.harness, "Antigravity CLI 1.1.25")
        self.assertEqual(n.model, "Gemini 3.8 Flash (High)")
        self.assertEqual(n.recorded_at, "2026-09-04 01:03:57 UTC")
        self.assertEqual(len(n.prompts), 2)
        self.assertEqual(n.prompts[0].timestamp, "2026-09-04 01:03:57")
        self.assertEqual(n.prompts[0].text, "Make the camera pivot around the ball origin")
        self.assertEqual(n.prompts[1].timestamp, "2026-09-04 01:09:25")
        self.assertIn("Second line of prompt.", n.prompts[1].text)

        # Roundtrip formatting
        formatted = gpn.serialize_notes(notes)
        self.assertIn("Assistant-Session:", formatted)
        roundtrip_notes = gpn.parse_notes(formatted)
        self.assertEqual(len(roundtrip_notes), 1)
        self.assertEqual(roundtrip_notes[0].session_id, n.session_id)
        self.assertEqual(len(roundtrip_notes[0].prompts), 2)

    def test_multi_session_parse(self):
        raw = """Assistant-Session: session-aaa
Assistant-Harness: Antigravity CLI 1.1.24
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-01 10:00:00 UTC

Assistant-Prompts:
  [2026-09-01 10:00:00] Initial prompt

---

Assistant-Session: session-bbb
Assistant-Harness: Antigravity CLI 1.1.25
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-04 01:00:00 UTC

Assistant-Prompts:
  [2026-09-04 01:00:00] Followup prompt
"""
        notes = gpn.parse_notes(raw)
        self.assertEqual(len(notes), 2)
        self.assertEqual(notes[0].session_id, "session-aaa")
        self.assertEqual(notes[1].session_id, "session-bbb")

    def test_surrounding_non_prompt_notes_preserved(self):
        raw = """Reviewed and approved by QA team.

Assistant-Session: session-xyz
Assistant-Harness: Antigravity CLI 1.1.25
Assistant-Model: Gemini 3.8 Flash (High)
Assistant-Recorded: 2026-09-04 01:00:00 UTC

Assistant-Prompts:
  [2026-09-04 01:00:00] Add camera zoom feature

Deploy-ID: 98124
"""
        prefix, block, suffix = gpn.extract_prompt_block(raw)
        self.assertEqual(prefix, "Reviewed and approved by QA team.")
        self.assertEqual(suffix, "Deploy-ID: 98124")
        self.assertIn("Assistant-Session: session-xyz", block)
        self.assertIn("Add camera zoom feature", block)

        parsed = gpn.parse_notes(raw)
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0].session_id, "session-xyz")

        # Rewrapping preserves prefix and suffix
        reconstructed = gpn.wrap_prompt_block(block, prefix=prefix, suffix=suffix)
        self.assertIn("Reviewed and approved by QA team.", reconstructed)
        self.assertIn("Deploy-ID: 98124", reconstructed)


class TestNoteMerging(unittest.TestCase):
    def test_same_session_squash_merge(self):
        note1 = gpn.SessionNote(
            session_id="session-1",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:05:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-04 01:03:57", "First prompt"),
            ],
        )
        note2 = gpn.SessionNote(
            session_id="session-1",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:10:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-04 01:03:57", "First prompt"),  # Duplicate
                gpn.PromptEntry("2026-09-04 01:09:25", "Second prompt"),
            ],
        )

        merged = gpn.merge_session_notes([note1, note2])
        self.assertEqual(len(merged), 1)
        m = merged[0]
        self.assertEqual(m.session_id, "session-1")
        self.assertEqual(m.recorded_at, "2026-09-04 01:10:00 UTC")  # Latest timestamp
        self.assertEqual(len(m.prompts), 2)
        self.assertEqual(m.prompts[0].text, "First prompt")
        self.assertEqual(m.prompts[1].text, "Second prompt")

    def test_cross_session_squash_merge(self):
        note1 = gpn.SessionNote(
            session_id="session-day-1",
            harness="Antigravity CLI 1.1.24",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-01 10:00:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-01 09:50:00", "Prompt from day 1"),
            ],
        )
        note2 = gpn.SessionNote(
            session_id="session-day-2",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:10:00 UTC",
            prompts=[
                gpn.PromptEntry("2026-09-04 01:09:25", "Prompt from day 2"),
            ],
        )

        merged = gpn.merge_session_notes([note1, note2])
        self.assertEqual(len(merged), 2)
        self.assertEqual(merged[0].session_id, "session-day-1")
        self.assertEqual(merged[1].session_id, "session-day-2")

        serialized = gpn.serialize_notes(merged)
        self.assertIn("Assistant-Session: session-day-1", serialized)
        self.assertIn("Assistant-Session: session-day-2", serialized)
        self.assertIn("\n\n---\n\n", serialized)


class TestGitPostRewriteIntegration(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.mkdtemp()
        self.repo_dir = Path(self.tmp_dir)

        # Initialize git repo
        subprocess.run(["git", "init"], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=self.repo_dir, check=True)

    def tearDown(self):
        shutil.rmtree(self.tmp_dir)

    def _commit(self, filename: str, content: str, msg: str) -> str:
        fpath = self.repo_dir / filename
        fpath.write_text(content)
        subprocess.run(["git", "add", filename], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "commit", "-m", msg], cwd=self.repo_dir, check=True, capture_output=True)
        out = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        return out

    def test_post_rewrite_squash(self):
        sha1 = self._commit("file1.txt", "hello", "Commit 1")
        sha2 = self._commit("file2.txt", "world", "Commit 2")

        # Attach prompt notes to sha1 and sha2
        note1 = gpn.SessionNote(
            session_id="session-test",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:05:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 01:03:00", "Create file 1")],
        )
        note2 = gpn.SessionNote(
            session_id="session-test",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:10:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 01:08:00", "Create file 2")],
        )
        gpn.write_note_content(sha1, note1.format(), repo_root=self.repo_dir)
        gpn.write_note_content(sha2, note2.format(), repo_root=self.repo_dir)

        # Simulate a squash into sha3
        sha3 = self._commit("file3.txt", "squashed", "Squashed Commit")

        # Simulate git post-rewrite stdin:
        # <sha1> <sha3>
        # <sha2> <sha3>
        stdin_data = f"{sha1} {sha3}\n{sha2} {sha3}\n"

        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "post-rewrite"],
            cwd=self.repo_dir,
            input=stdin_data,
            text=True,
            capture_output=True,
        )
        self.assertEqual(res.returncode, 0)

        # Verify sha3 has the merged note
        note_sha3_raw = gpn.get_note_content(sha3, repo_root=self.repo_dir)
        self.assertIsNotNone(note_sha3_raw)
        parsed = gpn.parse_notes(note_sha3_raw)
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0].session_id, "session-test")
        self.assertEqual(len(parsed[0].prompts), 2)
        self.assertEqual(parsed[0].prompts[0].text, "Create file 1")
        self.assertEqual(parsed[0].prompts[1].text, "Create file 2")

    def test_install_hook_installs_hooks_by_default(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "install-hook"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertTrue(os.access(hooks_dir / "post-rewrite", os.X_OK))
        # post-commit is installed by default
        self.assertTrue((hooks_dir / "post-commit").exists())
        self.assertTrue(os.access(hooks_dir / "post-commit", os.X_OK))

    def test_install_hook_no_post_commit(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "install-hook", "--no-post-commit"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertFalse((hooks_dir / "post-commit").exists())

    def test_post_commit_silent_when_no_agent_env(self):
        sha = self._commit("file.txt", "content", "Manual commit")
        script_path = Path(gpn.__file__).resolve()
        # Run without AGY_SESSION_ID or ANTIGRAVITY_CONVERSATION_ID
        env = os.environ.copy()
        env.pop("AGY_SESSION_ID", None)
        env.pop("ANTIGRAVITY_CONVERSATION_ID", None)
        res = subprocess.run(
            ["python3", str(script_path), "post-commit"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
            env=env,
        )
        self.assertEqual(res.returncode, 0)
        # Should not attach any note to human commit
        self.assertIsNone(gpn.get_note_content(sha, repo_root=self.repo_dir))

    def test_init_installs_hook_config_and_skill(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        # 1. Hooks installed
        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertTrue(os.access(hooks_dir / "post-rewrite", os.X_OK))
        self.assertTrue((hooks_dir / "post-commit").exists())
        self.assertTrue(os.access(hooks_dir / "post-commit", os.X_OK))

        # 2. Local git config set
        cfg_res = subprocess.check_output(
            ["git", "config", "--local", "notes.rewriteRef"],
            cwd=self.repo_dir,
            text=True,
        ).strip()
        self.assertEqual(cfg_res, "refs/notes/commits")

        # 3. Local skill installed
        skill_file = self.repo_dir / ".agents" / "skills" / "agy-prompt-note" / "SKILL.md"
        self.assertTrue(skill_file.exists())
        self.assertIn("agy-prompt-note", skill_file.read_text(encoding="utf-8"))

    def test_init_no_post_commit(self):
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "init", "--no-post-commit"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)

        hooks_dir = self.repo_dir / ".git" / "hooks"
        self.assertTrue((hooks_dir / "post-rewrite").exists())
        self.assertFalse((hooks_dir / "post-commit").exists())


class TestExportAndImportLog(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.repo_dir = Path(self.temp_dir.name)
        subprocess.run(["git", "init"], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test User"], cwd=self.repo_dir, check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=self.repo_dir, check=True)

    def tearDown(self):
        self.temp_dir.cleanup()

    def _commit(self, filename: str, content: str, msg: str) -> str:
        fpath = self.repo_dir / filename
        fpath.write_text(content)
        subprocess.run(["git", "add", filename], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "commit", "-m", msg], cwd=self.repo_dir, check=True, capture_output=True)
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()

    def test_export_and_import_exact(self):
        sha = self._commit("file1.txt", "v1", "feat: Feature one")
        note = gpn.SessionNote(
            session_id="session-export-1",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:00:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 00:59:00", "Build feature one")],
        )
        gpn.write_note_content(sha, note.format(), repo_root=self.repo_dir)

        # Export log
        out_file = self.repo_dir / "prompts" / "test_export.md"
        script_path = Path(gpn.__file__).resolve()
        res = subprocess.run(
            ["python3", str(script_path), "export-log", "--output", str(out_file), "--range", "HEAD~1..HEAD"],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res.returncode, 0)
        self.assertTrue(out_file.exists())
        log_content = out_file.read_text(encoding="utf-8")
        self.assertIn("# Prompt Log", log_content)
        self.assertIn("Build feature one", log_content)
        self.assertIn("<!-- git-prompt-note:metadata", log_content)

        # Remove note
        subprocess.run(["git", "notes", "remove", sha], cwd=self.repo_dir, check=True, capture_output=True)
        self.assertIsNone(gpn.get_note_content(sha, repo_root=self.repo_dir))

        # Import log back
        res_import = subprocess.run(
            ["python3", str(script_path), "import-log", str(out_file)],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res_import.returncode, 0)

        # Note restored
        restored = gpn.get_note_content(sha, repo_root=self.repo_dir)
        self.assertIsNotNone(restored)
        notes = gpn.parse_notes(restored)
        self.assertEqual(len(notes), 1)
        self.assertEqual(notes[0].session_id, "session-export-1")
        self.assertEqual(notes[0].prompts[0].text, "Build feature one")

    def test_import_reconciles_squashed_commit(self):
        sha1 = self._commit("file1.txt", "v1", "feat: Target Feature")
        note = gpn.SessionNote(
            session_id="session-squash-import",
            harness="Antigravity CLI 1.1.25",
            model="Gemini 3.8 Flash (High)",
            recorded_at="2026-09-04 01:00:00 UTC",
            prompts=[gpn.PromptEntry("2026-09-04 00:59:00", "Steer feature")],
        )
        gpn.write_note_content(sha1, note.format(), repo_root=self.repo_dir)

        out_file = self.repo_dir / "prompts" / "feature.md"
        script_path = Path(gpn.__file__).resolve()
        subprocess.run(
            ["python3", str(script_path), "export-log", "--output", str(out_file)],
            cwd=self.repo_dir,
            check=True,
            capture_output=True,
        )

        # Simulate commit amendment with different hash but same subject
        subprocess.run(["git", "notes", "remove", sha1], cwd=self.repo_dir, check=True, capture_output=True)
        f = self.repo_dir / "file2.txt"
        f.write_text("v2")
        subprocess.run(["git", "add", "."], cwd=self.repo_dir, check=True, capture_output=True)
        subprocess.run(["git", "commit", "--amend", "-m", "feat: Target Feature"], cwd=self.repo_dir, check=True, capture_output=True)
        sha_squashed = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=self.repo_dir, text=True).strip()
        self.assertNotEqual(sha1, sha_squashed)

        # Import log should reconcile sha_squashed by subject match
        res_import = subprocess.run(
            ["python3", str(script_path), "import-log", str(out_file)],
            cwd=self.repo_dir,
            capture_output=True,
            text=True,
        )
        self.assertEqual(res_import.returncode, 0)
        reconciled = gpn.get_note_content(sha_squashed, repo_root=self.repo_dir)
        self.assertIsNotNone(reconciled)
        notes = gpn.parse_notes(reconciled)
        self.assertEqual(len(notes), 1)
        self.assertEqual(notes[0].prompts[0].text, "Steer feature")


if __name__ == "__main__":
    unittest.main()
